# report.py
# Author: Jagger Hershey
#
# Runs the full CTD analysis suite (meta.py + analyze.py) and writes everything each function
# prints into one text file, so a presentation can be built by reading one document instead of
# re-running scripts and scrolling back through terminal history. Figures are still generated by
# the individual functions but aren't captured here - this is a text-only summary.
import sys
import contextlib
from pathlib import Path

import matplotlib
matplotlib.use('Agg')  # figures still get built internally; just don't block on plt.show()
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / 'common'))
from db import connect
import meta
import analyze

REPORT_PATH = Path(__file__).resolve().parent.parent.parent / 'data' / 'analysis_report.txt'


def generate_report(out_path=None):
    out_path = Path(out_path) if out_path else REPORT_PATH
    con = connect(read_only=True)

    def section(title):
        print(f"\n\n{'#' * 70}\n# {title}\n{'#' * 70}\n")

    with open(out_path, 'w', encoding='utf-8') as f, contextlib.redirect_stdout(f):
        print("CTD Toxic Exposure Analysis Report")

        section("Database Schema")
        meta.save_schema(con)

        section("Whole-Database Overview")
        meta.summarize_bulk(con)
        meta.gene_distribution(con)
        meta.interaction_type_distribution(con, human_only=True)

        section("Chemical-Gene / Chemical-Disease Field Analysis")
        analyze.file_analysis(con)

        section("GeneForm x Interaction Type")
        analyze.geneform_type_distribution(con, human_only=True)

        section("Gene Hub-Score Distribution")
        analyze.gene_hub_distribution(con)

        section("Chemicals Common Among Hub vs Specific Genes")
        analyze.chemical_hub_specific_overlap(con)

        section("Rare Interaction Type Deep Dives")
        for rare_type in ("myristoylation", "polymerization", "ribosylation"):
            analyze.type_disease_links(con, rare_type)
            analyze.build_type_disease_network(con, rare_type)

        section("High-Volume Interaction Type Deep Dives")
        analyze.type_disease_links(con, "binding", limit=25)
        analyze.build_type_disease_network(con, "binding", limit=25)
        analyze.type_disease_links(con, "folding", limit=25)
        analyze.build_type_disease_network(con, "folding", limit=25)

        section("ATSDR Top 15 Toxic Substances")
        analyze.atsdr_top_chemical_patterns(con)

    con.close()
    plt.close('all')
    print(f"Report written to {out_path}")


if __name__ == "__main__":
    generate_report()
